import { Integration, AIRoute } from '@/types';

export const integrations: Integration[] = [
  {
    id: 'int-1',
    name: 'PagerDuty',
    description: 'On-call scheduling, alerting, and escalation policies',
    category: 'alerting',
    status: 'connected',
    icon: 'bell',
    connectedAt: '2024-01-15T00:00:00Z',
    lastSync: '2026-07-04T14:30:00Z',
    webhookUrl: 'https://events.pagerduty.com/integration/abc123',
  },
  {
    id: 'int-2',
    name: 'Datadog',
    description: 'Infrastructure monitoring, APM, and log management',
    category: 'monitoring',
    status: 'connected',
    icon: 'activity',
    connectedAt: '2024-01-15T00:00:00Z',
    lastSync: '2026-07-04T14:28:00Z',
    webhookUrl: null,
  },
  {
    id: 'int-3',
    name: 'Slack',
    description: 'Team notifications and incident channel automation',
    category: 'communication',
    status: 'connected',
    icon: 'message-square',
    connectedAt: '2024-02-01T00:00:00Z',
    lastSync: '2026-07-04T14:31:00Z',
    webhookUrl: 'https://hooks.slack.com/services/T00/B00/xxx',
  },
  {
    id: 'int-4',
    name: 'Jira',
    description: 'Automatic ticket creation and incident tracking',
    category: 'ticketing',
    status: 'connected',
    icon: 'ticket',
    connectedAt: '2024-03-10T00:00:00Z',
    lastSync: '2026-07-04T12:00:00Z',
    webhookUrl: null,
  },
  {
    id: 'int-5',
    name: 'AWS CloudWatch',
    description: 'AWS resource metrics, alarms, and log insights',
    category: 'monitoring',
    status: 'connected',
    icon: 'cloud',
    connectedAt: '2024-01-20T00:00:00Z',
    lastSync: '2026-07-04T14:29:00Z',
    webhookUrl: null,
  },
  {
    id: 'int-6',
    name: 'Prometheus',
    description: 'Open-source metrics collection and alerting',
    category: 'monitoring',
    status: 'connected',
    icon: 'gauge',
    connectedAt: '2024-04-01T00:00:00Z',
    lastSync: '2026-07-04T14:30:00Z',
    webhookUrl: null,
  },
  {
    id: 'int-7',
    name: 'GitHub Actions',
    description: 'CI/CD pipeline events and deployment tracking',
    category: 'deployment',
    status: 'connected',
    icon: 'git-branch',
    connectedAt: '2024-05-15T00:00:00Z',
    lastSync: '2026-07-04T11:00:00Z',
    webhookUrl: 'https://api.github.com/hooks/xxx',
  },
  {
    id: 'int-8',
    name: 'OpsGenie',
    description: 'Alert management and on-call rotations',
    category: 'alerting',
    status: 'disconnected',
    icon: 'bell-ring',
    connectedAt: null,
    lastSync: null,
    webhookUrl: null,
  },
  {
    id: 'int-9',
    name: 'Microsoft Teams',
    description: 'Enterprise communication and incident bridges',
    category: 'communication',
    status: 'disconnected',
    icon: 'users',
    connectedAt: null,
    lastSync: null,
    webhookUrl: null,
  },
  {
    id: 'int-10',
    name: 'ServiceNow',
    description: 'ITSM platform integration for enterprise workflows',
    category: 'ticketing',
    status: 'pending',
    icon: 'layers',
    connectedAt: null,
    lastSync: null,
    webhookUrl: null,
  },
  {
    id: 'int-11',
    name: 'Google Cloud Monitoring',
    description: 'GCP infrastructure and application monitoring',
    category: 'cloud',
    status: 'error',
    icon: 'cloud-lightning',
    connectedAt: '2024-06-01T00:00:00Z',
    lastSync: '2026-07-03T08:00:00Z',
    webhookUrl: null,
  },
  {
    id: 'int-12',
    name: 'Grafana',
    description: 'Dashboard and visualization platform',
    category: 'monitoring',
    status: 'connected',
    icon: 'bar-chart-2',
    connectedAt: '2024-03-20T00:00:00Z',
    lastSync: '2026-07-04T14:15:00Z',
    webhookUrl: null,
  },
];

export const aiRoutes: AIRoute[] = [
  {
    id: 'route-1',
    name: 'Incident Triage',
    description: 'Fast severity classification and initial assessment',
    provider: 'groq',
    model: 'llama-3.3-70b-versatile',
    useCases: ['severity-classification', 'initial-triage', 'impact-estimation'],
    avgLatencyMs: 420,
    costPerRequest: 0.0008,
    isActive: true,
    requestCount: 12847,
    successRate: 99.2,
  },
  {
    id: 'route-2',
    name: 'Root Cause Analysis',
    description: 'Deep incident analysis with historical context',
    provider: 'groq',
    model: 'llama-3.3-70b-versatile',
    useCases: ['root-cause', 'correlation', 'pattern-matching'],
    avgLatencyMs: 1840,
    costPerRequest: 0.0024,
    isActive: true,
    requestCount: 4291,
    successRate: 97.8,
  },
  {
    id: 'route-3',
    name: 'Runbook Generation',
    description: 'AI-generated recovery procedures and runbooks',
    provider: 'groq',
    model: 'llama-3.3-70b-versatile',
    useCases: ['runbook-gen', 'recovery-steps', 'documentation'],
    avgLatencyMs: 2100,
    costPerRequest: 0.0031,
    isActive: true,
    requestCount: 1823,
    successRate: 96.4,
  },
  {
    id: 'route-4',
    name: 'Postmortem Drafting',
    description: 'Automated postmortem document generation',
    provider: 'groq',
    model: 'llama-3.3-70b-versatile',
    useCases: ['postmortem', 'blameless-review', 'action-items'],
    avgLatencyMs: 3200,
    costPerRequest: 0.0045,
    isActive: false,
    requestCount: 342,
    successRate: 94.1,
  },
];
