import { TeamMember, Organization, Team } from '@/types';

export const organizations: Organization[] = [
  {
    id: 'org-1',
    name: 'CloudNova Technologies',
    slug: 'cloudnova',
    avatarColor: '#3B82F6',
    plan: 'enterprise',
    memberCount: 142,
  },
  {
    id: 'org-2',
    name: 'Vertex Payments',
    slug: 'vertex-pay',
    avatarColor: '#8B5CF6',
    plan: 'enterprise',
    memberCount: 89,
  },
  {
    id: 'org-3',
    name: 'BluePeak Systems',
    slug: 'bluepeak',
    avatarColor: '#10B981',
    plan: 'pro',
    memberCount: 54,
  },
  {
    id: 'org-4',
    name: 'SkyScale Cloud',
    slug: 'skyscale',
    avatarColor: '#06B6D4',
    plan: 'pro',
    memberCount: 31,
  },
];

export const currentOrg = organizations[0];

export const teamMembers: TeamMember[] = [
  {
    id: 'usr-1',
    name: 'Harshini Shree',
    email: 'harshini@cloudnova.io',
    role: 'incident-commander',
    avatarInitials: 'HS',
    avatarColor: '#3B82F6',
    team: 'Platform Engineering',
    status: 'online',
    incidentsResolved: 247,
    joinedAt: '2022-03-15T00:00:00Z',
  },
  {
    id: 'usr-2',
    name: 'Priya Menon',
    email: 'priya.menon@cloudnova.io',
    role: 'sre',
    avatarInitials: 'PM',
    avatarColor: '#10B981',
    team: 'SRE',
    status: 'online',
    incidentsResolved: 189,
    joinedAt: '2021-08-20T00:00:00Z',
  },
  {
    id: 'usr-3',
    name: 'Rohan Kapoor',
    email: 'rohan.kapoor@cloudnova.io',
    role: 'devops',
    avatarInitials: 'RK',
    avatarColor: '#8B5CF6',
    team: 'Cloud Infrastructure',
    status: 'away',
    incidentsResolved: 134,
    joinedAt: '2023-01-10T00:00:00Z',
  },
  {
    id: 'usr-4',
    name: 'Kavita Reddy',
    email: 'kavita.reddy@cloudnova.io',
    role: 'sre',
    avatarInitials: 'KR',
    avatarColor: '#F59E0B',
    team: 'SRE',
    status: 'online',
    incidentsResolved: 98,
    joinedAt: '2023-06-01T00:00:00Z',
  },
  {
    id: 'usr-5',
    name: 'Dev Anand',
    email: 'dev.anand@cloudnova.io',
    role: 'admin',
    avatarInitials: 'DA',
    avatarColor: '#EF4444',
    team: 'Security Operations',
    status: 'online',
    incidentsResolved: 312,
    joinedAt: '2020-11-05T00:00:00Z',
  },
  {
    id: 'usr-6',
    name: 'Sneha Iyer',
    email: 'sneha.iyer@cloudnova.io',
    role: 'devops',
    avatarInitials: 'SI',
    avatarColor: '#06B6D4',
    team: 'DevOps',
    status: 'offline',
    incidentsResolved: 76,
    joinedAt: '2024-02-14T00:00:00Z',
  },
];

export const teams: Team[] = [
  {
    id: 'team-1',
    name: 'Platform Engineering',
    description: 'Core platform stability and developer experience',
    memberCount: 18,
    lead: 'Harshini Shree',
    oncallCount: 3,
  },
  {
    id: 'team-2',
    name: 'Cloud Infrastructure',
    description: 'AWS, GCP and Kubernetes fleet management',
    memberCount: 12,
    lead: 'Rohan Kapoor',
    oncallCount: 2,
  },
  {
    id: 'team-3',
    name: 'SRE',
    description: 'Reliability engineering and SLA ownership',
    memberCount: 9,
    lead: 'Priya Menon',
    oncallCount: 4,
  },
  {
    id: 'team-4',
    name: 'Security Operations',
    description: 'Threat detection, compliance and audit',
    memberCount: 7,
    lead: 'Dev Anand',
    oncallCount: 2,
  },
  {
    id: 'team-5',
    name: 'DevOps',
    description: 'CI/CD pipelines, deployments and automation',
    memberCount: 14,
    lead: 'Sneha Iyer',
    oncallCount: 2,
  },
];

export const currentUser = teamMembers[0];
